services:
  fuseki:
    image: secoresearch/fuseki:5.1.0
    ports:
      - "3030:3030"
    volumes:
      - ./config.ttl:/fuseki/config.ttl
      - ./data:/fuseki/databases
    environment:
      - FUSEKI_CONFIG_FILE=/fuseki/config.ttl
      - ADMIN_PASSWORD=password
    command: ["/jena-fuseki/fuseki-server"]